"""Financial news tool - gnews API.

Gives the agent access to real-time financial news for trading analysis,
market sentiment, corporate news, earnings announcements, and regulatory updates.
"""
from __future__ import annotations

import asyncio
import json
import urllib.request
import urllib.error
from langchain_core.tools import tool

try:
    from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
    analyzer = SentimentIntensityAnalyzer()
    HAS_VADER = True
except ImportError:
    HAS_VADER = False



async def fetch_gnews(query: str, max_results: int = 5) -> list:
    """Fetch raw JSON articles from gnews with fallback mock data."""
    print(f"📰 [FETCH] fetch_gnews called → query={query!r}")
    max_results = min(max(1, max_results), 100)
    
    # Try to fetch real news from gnews
    try:
        from gnews import GNews
        google_news = GNews(max_results=max_results * 2)
        loop = asyncio.get_event_loop()
        articles = await loop.run_in_executor(
            None, 
            google_news.get_news,
            query,
        )
        
        if articles:
            return _clean_articles(articles, max_results)
    except ImportError:
        print("⚠️ gnews not installed, using fallback")
    except Exception as e:
        print(f"⚠️ gnews fetch error: {e}")
    
    # Fallback to mock news data
    return _get_raw_mock_financial_news(query, max_results)


@tool
async def search_financial_news(query: str, max_results: int = 5) -> str:
    """
    Search for financial news using gnews API with fallback to mock data.
    
    Fetches real-time financial news articles from multiple sources. Each article includes an 
    `ML Classifier Sentiment` (Positive/Negative/Neutral) generated by a basic NLP classification model.
    
    CRITICAL INSTRUCTION FOR LLM:
    The ML Classifier Sentiment attached to each news article is a simple rule-based model. 
    You MUST read the news summary and use your innate knowledge about the specific company to 
    decide the FINAL sentiment impact (Positive, Negative, or Neutral) and explain how it affects the company.
    Do not just blindly trust the ML output.

    Args:
        query: The search query (e.g., "Apple earnings", "Fed interest rates")
        max_results: Number of results to return (default 5, max 100)
    
    Returns:
        Formatted string with news articles, summaries, and initial ML sentiments.
    """
    articles = await fetch_gnews(query, max_results)
    return _format_news_results(query, articles)


def _clean_articles(articles: list, max_results: int) -> list:
    """Clean and standardize gnews articles into dicts."""
    cleaned = []
    for article in articles:
        if len(cleaned) >= max_results:
            break
        try:
            if not isinstance(article, dict):
                continue
            
            title = article.get("title", "").strip()
            source = "Unknown"
            publisher_data = article.get("publisher")
            if isinstance(publisher_data, dict):
                source = publisher_data.get("title", "Unknown")
            elif publisher_data:
                source = str(publisher_data)
            url = article.get("url", "")
            summary = article.get("description") or article.get("summary", "")
            summary = summary.strip() if summary else ""
            published = article.get("published date", "")
            
            if not title:
                continue
            
            if summary and len(summary) > 300:
                summary = summary[:300] + "..."
                
            sentiment_label = "Neutral"
            if HAS_VADER:
                score = analyzer.polarity_scores(f"{title}. {summary}")['compound']
                if score >= 0.05:
                    sentiment_label = "Positive"
                elif score <= -0.05:
                    sentiment_label = "Negative"
            
            cleaned.append({
                "title": title,
                "source": source,
                "summary": summary,
                "url": url,
                "published": published,
                "ml_sentiment": sentiment_label
            })
        except (KeyError, TypeError, AttributeError):
            continue
    return cleaned


def _format_news_results(query: str, articles: list) -> str:
    """Format structured dict articles into readable markdown output for the LLM."""
    lines = [f"📰 Financial News: {query}\n"]
    
    if not articles:
        return "\n".join(lines) + "No articles found."
    
    # Process articles
    count = 0
    for article in articles:
        if count >= 20: # arbitrary cap
            break
        
        try:
            title = article.get("title", "")
            source = article.get("source", "Unknown")
            url = article.get("url", "")
            summary = article.get("summary", "")
            ml_sentiment = article.get("ml_sentiment", "")
            
            lines.append(f"**[{count + 1}] {title}**")
            lines.append(f"Source: {source}")
            if ml_sentiment:
                lines.append(f"ML Classifier Sentiment: {ml_sentiment}")
            if summary:
                lines.append(summary)
            if url:
                lines.append(f"URL: {url}")
            lines.append("")
            
            count += 1
        except Exception:
            continue
    
    if count == 0:
        return "\n".join(lines) + "No valid articles found."
    
    return "\n".join(lines)


def _get_raw_mock_financial_news(query: str, max_results: int) -> list:
    """Fallback mock financial news data arrays."""
    mock_articles = [
        {
            "title": "NVIDIA Q1 Earnings Beat Analyst Expectations by 25%",
            "source": "Reuters",
            "summary": "NVIDIA reported revenue of $26.1 billion for Q1, exceeding consensus estimates by $6.5 billion. Gross margins expanded to 75% driven by strong AI datacenter demand.",
            "url": "https://reuters.com/nvidia-q1",
            "published": "2 hours ago"
        },
        {
            "title": "Federal Reserve Signals Possibility of Rate Cuts by Q3",
            "source": "Bloomberg",
            "summary": "Fed officials indicated in FOMC meeting that interest rate reductions may be warranted if inflation continues on downward trajectory. Market rallied on dovish commentary.",
            "url": "https://bloomberg.com/fed-rates",
            "published": "4 hours ago"
        },
        {
            "title": "Apple Announces New AI Integration Across All Products",
            "source": "CNBC",
            "summary": "Apple unveiled comprehensive AI features for iPhone, Mac, and iPad during developer conference. Stock jumped 3% on announcement.",
            "url": "https://cnbc.com/apple-ai",
            "published": "1 day ago"
        },
        {
            "title": "Treasury Yields Decline Amid Economic Slowdown Concerns",
            "source": "Financial Times",
            "summary": "10-year Treasury yields fell 18 basis points to 4.12% as investors seek safe-haven assets. Mixed employment data fuels recession debate.",
            "url": "https://ft.com/treasuries",
            "published": "1 day ago"
        },
        {
            "title": "Energy Markets Rally on Middle East Supply Disruptions",
            "source": "MarketWatch",
            "summary": "Oil futures climbed 3.2% as geopolitical tensions threaten supply from key regions. WTI crude reached $93 per barrel, highest in 6 weeks.",
            "url": "https://marketwatch.com/energy",
            "published": "2 days ago"
        },
    ]
    
    # Filter based on query relevance (simple keyword matching)
    query_lower = query.lower()
    relevant = []
    for article in mock_articles:
        if any(word in article["title"].lower() for word in query_lower.split()):
            relevant.append(article)
    
    # Use relevant articles if found, otherwise use all
    articles_to_show = relevant if relevant else mock_articles
    articles_to_show = articles_to_show[:max_results]
    
    for item in articles_to_show:
        sentiment_label = "Neutral"
        if HAS_VADER:
            score = analyzer.polarity_scores(f"{item['title']}. {item['summary']}")['compound']
            if score >= 0.05:
                sentiment_label = "Positive"
            elif score <= -0.05:
                sentiment_label = "Negative"
        item["ml_sentiment"] = sentiment_label
        
    return articles_to_show


async def fetch_sector_sentiment(num_news: int, headlines: list[str]) -> dict:
    """Fetch sentiment from HF Space API using externally-fetched headlines."""
    url = "https://SaqlainSQX-iii5-backend.hf.space/sector-sentiment-headlines"
    data = json.dumps({"num_news": num_news, "headlines": headlines}).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"}, method="POST")

    loop = asyncio.get_event_loop()
    
    def _do_request():
        try:
            with urllib.request.urlopen(req) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.URLError as e:
            print(f"⚠️ HF Space API fetch error: {e}")
            return None
        except Exception as e:
            print(f"⚠️ Unexpected error: {e}")
            return None

    return await loop.run_in_executor(None, _do_request)


async def fetch_sector_headlines(sector: str, desired_count: int = 50) -> list[str]:
    """
    Fetch headlines outside the sentiment API.
    Ensures exactly `desired_count` non-empty strings.
    """
    desired_count = max(1, desired_count)
    queries = [
        f"{sector} stock market",
        f"{sector} stocks",
        f"{sector} finance",
        sector,
    ]
    unique: list[str] = []
    seen = set()
    for q in queries:
        articles = await fetch_gnews(q, max_results=desired_count)
        for article in articles:
            title = str(article.get("title", "")).strip()
            key = title.lower()
            if title and key not in seen:
                seen.add(key)
                unique.append(title)
            if len(unique) >= desired_count:
                return unique[:desired_count]

    # deterministic fallback filler if providers return fewer than requested
    i = 1
    while len(unique) < desired_count:
        filler = f"{sector} market update headline {i}"
        unique.append(filler)
        i += 1
    return unique[:desired_count]


@tool
async def analyze_sector_sentiment(sector: str) -> str:
    """
    Analyzes sentiment for a market sector by:
    1) fetching 50 headlines in this tool, then
    2) sending only headlines to the backend sentiment API.
    
    Use this tool to get positive, negative, and neutral sentiment breakdowns, 
    an overall sentiment score, and a trading signal (BULLISH/BEARISH/NEUTRAL) for a given sector.
    
    Args:
        sector: The market sector to analyze (e.g., "Technology", "Energy", "Finance", "Healthcare")
    
    Returns:
        Formatted string containing the sentiment breakdown, scores, and signals.
    """
    print(f"📊 [SENTIMENT] analyze_sector_sentiment called → sector={sector!r}")
    headlines = await fetch_sector_headlines(sector, desired_count=50)
    data = await fetch_sector_sentiment(len(headlines), headlines)
    
    if not data:
        return f"Could not fetch sentiment for sector: {sector}. The backend service might be unavailable."
        
    lines = [
        f"📊 **Sector Sentiment Analysis: {sector}**",
        f"Total Headlines Analyzed: {data.get('total_headlines', 0)}",
        "",
        "**Sentiment Breakdown:**",
        f"- Positive: {data.get('positive', 0)} ({data.get('positive_pct', 0.0)}%)",
        f"- Negative: {data.get('negative', 0)} ({data.get('negative_pct', 0.0)}%)",
        f"- Neutral: {data.get('neutral', 0)} ({data.get('neutral_pct', 0.0)}%)",
        "",
        "**Overall Metrics:**",
        f"- Overall Sentiment: {data.get('overall_sentiment', 'UNKNOWN')}",
        f"- Sentiment Score: {data.get('sentiment_score', 0)}",
        f"- Signal: {data.get('signal', 'UNKNOWN')}",
    ]
    per_news = data.get("per_news_sentiment", [])
    if per_news:
        lines.append("")
        lines.append("**Per-Headline Sentiment (Top 5 shown):**")
        for item in per_news[:5]:
            lines.append(f"- [{item.get('sentiment', 'UNKNOWN')}] {item.get('headline', '')}")
    
    return "\n".join(lines)
